// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTPMQL_MVC.Data;

#nullable disable

namespace PTPMQL_MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505101854_DeviceCategory")]
    partial class DeviceCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.Device", b =>
                {
                    b.Property<int>("DeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceCategoryCategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceID");

                    b.HasIndex("DeviceCategoryCategoryID");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.DeviceCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("DeviceCategory");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.ExportDetail", b =>
                {
                    b.Property<int>("ExportDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExportReceiptID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ExportDetailID");

                    b.HasIndex("DeviceID");

                    b.HasIndex("ExportReceiptID");

                    b.ToTable("ExportDetail");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.ExportReceipt", b =>
                {
                    b.Property<int>("ExportReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExportDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ExportReceiptID");

                    b.ToTable("ExportReceipt");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.Faculty", b =>
                {
                    b.Property<string>("FacultyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.ImportDetail", b =>
                {
                    b.Property<int>("ImportDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportReceiptID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ImportDetailID");

                    b.HasIndex("DeviceID");

                    b.HasIndex("ImportReceiptID");

                    b.ToTable("ImportDetail");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.ImportReceipt", b =>
                {
                    b.Property<int>("ImportReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImportReceiptID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ImportReceipt");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.Student", b =>
                {
                    b.Property<string>("StudentCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentCode");

                    b.HasIndex("FacultyId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierId");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.Device", b =>
                {
                    b.HasOne("PTPMQL_MVC.Models.Entities.DeviceCategory", "DeviceCategory")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceCategoryCategoryID");

                    b.Navigation("DeviceCategory");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.ExportDetail", b =>
                {
                    b.HasOne("PTPMQL_MVC.Models.Entities.Device", "Device")
                        .WithMany("ExportDetails")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTPMQL_MVC.Models.Entities.ExportReceipt", "ExportReceipt")
                        .WithMany("ExportDetails")
                        .HasForeignKey("ExportReceiptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("ExportReceipt");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.ImportDetail", b =>
                {
                    b.HasOne("PTPMQL_MVC.Models.Entities.Device", "Device")
                        .WithMany("ImportDetails")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTPMQL_MVC.Models.Entities.ImportReceipt", "ImportReceipt")
                        .WithMany("ImportDetails")
                        .HasForeignKey("ImportReceiptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("ImportReceipt");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.ImportReceipt", b =>
                {
                    b.HasOne("PTPMQL_MVC.Models.Entities.Supplier", "Supplier")
                        .WithMany("ImportReceipts")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.Student", b =>
                {
                    b.HasOne("PTPMQL_MVC.Models.Entities.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.Device", b =>
                {
                    b.Navigation("ExportDetails");

                    b.Navigation("ImportDetails");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.DeviceCategory", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.ExportReceipt", b =>
                {
                    b.Navigation("ExportDetails");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.ImportReceipt", b =>
                {
                    b.Navigation("ImportDetails");
                });

            modelBuilder.Entity("PTPMQL_MVC.Models.Entities.Supplier", b =>
                {
                    b.Navigation("ImportReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
